---
- name: Combine default settings and user-defined variables
  set_fact: {"{{ item }}": "{% if vars[item] is not defined %}{{ defaults[item] }}{% elif vars[item] is mapping %}{{ defaults[item]|combine(vars[item]|default({})) }}{% else %}{{ vars[item] }}{% endif %}"}
  with_items: "{{ defaults.keys() }}"
  no_log: true

- name: Make sure devel_mode is not on
  assert:
    that:
      - devel_mode == False
      - use_epel == False
    msg: "Devel mode is not supported in the downstream builds"
